version: '3.8'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"     # Spark Master Web UI
      - "7077:7077"     # Spark Master Port
    networks:
      - spark-net
      - kafka-net

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - "8081:8081"     # Spark Worker Web UI
    depends_on:
      - spark-master
    networks:
      - spark-net
      - kafka-net

  spark-submit:
    image: bitnami/spark:latest
    container_name: spark-submit
    entrypoint: ["spark-submit"]
    networks:
      - spark-net
      - kafka-net
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      # Set any additional environment variables needed here

networks:
  spark-net:
    driver: bridge
  kafka-net:
    external: true
