version: '3.8'

services:
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT://kafka:9092  # Update 'localhost' as needed
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'           # Enable automatic topic creation
      KAFKA_BROKER_ID: 1                                # Unique broker ID
      KAFKA_LOG_DIRS: /kafka/kafka-logs                 # Directory for Kafka logs
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    volumes:                                           # Optional: Mount logs outside container for persistence
      - ./kafka-data:/kafka/kafka-logs

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
