project_id           = "your-actual-project-id"
region               = "us-central1"
zone                 = "us-central1-a"
kafka_machine_type   = "n1-standard-2"
spark_machine_type   = "n1-standard-4"
airflow_machine_type = "n1-standard-2"
bucket_name_prefix   = "my-data-pipeline-bucket"
bigquery_dataset_id  = "my_data_pipeline"
